name: SimilarityModeling
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=4.0.9
  - matplotlib=3.8.2
  - numpy=1.26.2
  - pandas=2.1.3
  - pip=23.3.1
  - python=3.11.0
  - scikit-learn=1.3.2
  - scipy=1.11.4
  - seaborn=0.13.0
  - ffmpeg=6.1.0
  - opencv=4.8.1
  - librosa=0.10.1
  - scikit-image
  - tqdm
  - pip:
      - ipywidgets==8.1.1
